lscrs : utilisation simplifiée

diff --git a/shell/lscrs b/shell/lscrs
--- a/shell/lscrs
+++ b/shell/lscrs
@@ -17,6 +17,8 @@ typeset -r str_usage=\
 	[-wait_time_secs=<#>]  Temps de pause entre chaque tentative.
 
 	-db et -server ne peuvent être utiliser en même temps.
+
+Autre utilisation : ${ME##*/} id est équivalent à ${ME##*/} -db=id
 "
 
 typeset		db=undef
@@ -47,11 +49,23 @@ do
 			shift
 			;;
 
-		*)
-			error "Arg '$1' invalid."
-			LN
+		-h|-help|help)
 			info "$str_usage"
+			LN
 			exit 1
+			;;
+
+		*)
+			if [ "$db" == undef ]
+			then
+				db=$1
+				shift
+			else
+				error "Arg '$1' invalid."
+				LN
+				info "$str_usage"
+				exit 1
+			fi
 			;;
 	esac
 done
@@ -75,31 +89,35 @@ fi
 if [ $server_name == undef ]
 then
 	if [ $nr_node -eq -1 ]
-	then #	Test si une scan existe.
-		cfg_exists $db use_return_code
-		if [ $? -eq 0 ]
-		then
-			typeset -ri max_nodes=$(cfg_max_nodes $db)
-			[ $max_nodes -gt 1 ] && server_name=$db-scan || true
-		fi
+	then
+		cfg_exists $db
+		typeset -ri max_nodes=$(cfg_max_nodes $db)
+		# Pour un RAC utilise l'adresse de scan.
+		[ $max_nodes -gt 1 ] && server_name=$db-scan || true
 	fi
+
 	[ $server_name == undef ] && server_name=$(printf "srv%s01" ${db}) || true
 fi
 
 wait_server $server_name
-[ $? -ne 0 ] && exit 1
+[ $? -ne 0 ] && exit 1 || true
 
 start_s=$SECONDS
 typeset -i wait_time_s=$wait_time_secs
-while [ 0 -eq 0 ]
+while true
 do
 	exec_cmd -c "ssh grid@$server_name \". ~/.profile; crsctl stat res -t\""
-	[ $? -eq 0 ] && exit 0
+	[ $? -eq 0 ] && exit 0 || true
 
 	info -n "Waiting : "; pause_in_secs $wait_time_s
 	duration=$(( $SECONDS - $start_s ))
 	info -f ", ${YELLOW}Total wait $(fmt_seconds $duration)${NORM}..."
 	LN
-	[ $wait_time_s -gt 60 ] && wait_time_s=wait_time_s-60
-	[[ $wait_time_secs -gt 60 && $wait_time_s -lt 60 ]] && wait_time_s=wait_time_secs
+
+	[ $wait_time_s -gt 60 ] && wait_time_s=wait_time_s-60 || true
+
+	if [[ $wait_time_secs -gt 60 && $wait_time_s -lt 60 ]]
+	then
+		wait_time_s=wait_time_secs
+	fi
 done
