Correction code retour du script.

diff --git a/shell/stop_vm b/shell/stop_vm
--- a/shell/stop_vm
+++ b/shell/stop_vm
@@ -37,7 +37,7 @@ function virtualbox_stop
 			LN
 			info "Poweroff : ${vm_list[$ivm]}"
 			exec_cmd -c "VBoxManage controlvm ${vm_list[$ivm]} poweroff"
-			[ $? -ne 0 ] && error "Failed to poweroff ${vm_list[$ivm]}"
+			[ $? -ne 0 ] && error "Failed to poweroff ${vm_list[$ivm]}" && exit 1
 		fi
 		LN
 	done
@@ -46,6 +46,7 @@ function virtualbox_stop
 case ${hostvm##*_} in
 	virtualbox)
 		virtualbox_stop
+		exit 0
 		;;
 
 	*)
