Nettoyage et revue de code
La correction principale est le nettoyage des caches arp des serveurs.

cfglib.sh
    Simplification message.

database_servers/clone_master.sh
    Si la VM clonée ne stop pas sur acpipowerbutton le script échoue.
    Purge du cache arp de l'ensemble des serveurs.

database_servers/cleanup_infra.sh
    Purge du cache arp de l'ensemble des serveurs.

database_servers/define_new_server.sh
    Correction aide.

database_servers/run_all.sh
    Restructuration du script.

db/create_db.sh
    Typo.

oracle_preinstall/run_all.sh
    Ajustement workaround yum.

plelib.sh
    Nettoyage/simplification code.

Ajout du paramètre -error_on_poweroff, si la VM ne stop pas correctement
le
script ne fait pas un poweroff mais retourne 1.
    virtualbox/stop_vm
    virtualbox/reboot_vm

shell/infra_status
    Affiche le statut du serveur d'infra.

virtualbox/vbox_version
    Affiche sur stdout la version de VirtualBox.

diff --git a/virtualbox/reboot_vm b/virtualbox/reboot_vm
--- a/virtualbox/reboot_vm
+++ b/virtualbox/reboot_vm
@@ -11,13 +11,51 @@ typeset -r str_usage=\
 
 script_banner $ME $*
 
-[[ $# -eq 0 ]] && [[ -v ID_DB ]] && server=$ID_DB || server=$1
+typeset server=undef
+typeset error_on_poweroff=no
 
-if [ x"$server" == x ]
-then
-	error "$str_usage"
-	exit 1
-fi
+while [ $# -ne 0 ]
+do
+	case $1 in
+		-emul)
+			EXEC_CMD_ACTION=NOP
+			shift
+			;;
+
+		-server=*)
+			server=${1##*=}
+			shift
+			;;
+
+		-error_on_poweroff)
+			error_on_poweroff=yes
+			shift
+			;;
+
+		-h|-help|help)
+			info "$str_usage"
+			LN
+			exit 1
+			;;
+
+		*)
+			if [ $server == undef ]
+			then
+				server=$1
+				shift
+			else
+				error "Arg '$1' invalid."
+				LN
+				info "$str_usage"
+				exit 1
+			fi
+			;;
+	esac
+done
+
+[[ "$server" == undef && -v ID_DB ]] && server=$ID_DB || true
+
+exit_if_param_undef server	"$str_usage"
 
 typeset	-a	running_vm_list
 
@@ -59,8 +97,16 @@ then
 	fi
 fi
 
-exec_cmd "stop_vm -server=$server"
-LN
+case $error_on_poweroff in
+	no)
+		exec_cmd "stop_vm -server=$server"
+		LN
+		;;
+	yes)
+		exec_cmd "stop_vm -server=$server -error_on_poweroff"
+		LN
+		;;
+esac
 
 exec_cmd "start_vm $server -wait_os=no"
 LN
diff --git a/virtualbox/stop_vm b/virtualbox/stop_vm
--- a/virtualbox/stop_vm
+++ b/virtualbox/stop_vm
@@ -11,6 +11,7 @@ typeset -r str_usage=\
 	-server=<nom de la VM> si omis essait la variable ID_DB
 	[-wait_os=yes] : no n'aattend pas que l'OS soit stoppé avant de rendre la main.
 	[-reboot_vbox] : reboot tous les composants de vbox.
+	[-error_on_poweroff] : si un poweroff est nécessaire retourn 1
 "
 
 script_banner $ME $@
@@ -18,13 +19,13 @@ script_banner $ME $@
 typeset server=undef
 typeset	wait_os=yes
 typeset reboot_vbox=no
+typeset error_on_poweroff=no
 
 while [ $# -ne 0 ]
 do
 	case $1 in
 		-emul)
 			EXEC_CMD_ACTION=NOP
-			first_args=-emul
 			shift
 			;;
 
@@ -40,6 +41,11 @@ do
 
 		-reboot_vbox)
 			reboot_vbox=yes
+			shift
+			;;
+
+		-error_on_poweroff)
+			error_on_poweroff=yes
 			shift
 			;;
 
@@ -74,13 +80,15 @@ function wait_os_until_stopped
 	typeset	-ri	wait_max_secs=120
 	typeset	-i	secs=0
 
+	typeset tod_color
+
 	hide_cursor
 	info -n "Server $os_name stopping "
 	while [ 0 -eq 0 ]
 	do
 		VBoxManage list runningvms | grep -q $os_name
 		[ $? -eq 1 ] && LN && break
-		info -f -n "."
+		info -f -n "${tod_color}.${NORM}"
 		if [ $secs -eq $wait_max_secs ]
 		then
 			LN
@@ -90,6 +98,16 @@ function wait_os_until_stopped
 		elif [[ $secs -ne 0 && $(( secs % 10 )) -eq 0 ]]
 		then
 			info -f -n "${secs}s"
+			if [[ $secs -ge 30 && $secs -lt 60 ]]
+			then
+				tod_color=$PINK
+			elif [[ $secs -ge 60 && $sec -lt 90 ]]
+			then
+				tod_color=$YELLOW
+			elif [[ $sec -ge 90 ]]
+			then
+				tod_color=$RED
+			fi
 		fi
 		sleep 1
 		secs=secs+1
@@ -129,13 +147,18 @@ do
 		error "Failed to stop $vm"
 		LN
 
-		line_separator
-		info "Poweroff : $vm"
-		exec_cmd -c "VBoxManage controlvm $vm poweroff"
-		if [ $? -ne 0 ]
+		if [ $error_on_poweroff == yes ]
 		then
-			error "Failed to poweroff $vm"
 			count_errors=count_errors+1
+		else
+			line_separator
+			info "Poweroff : $vm"
+			exec_cmd -c "VBoxManage controlvm $vm poweroff"
+			if [ $? -ne 0 ]
+			then
+				error "Failed to poweroff $vm"
+				count_errors=count_errors+1
+			fi
 		fi
 	else
 		vm_stopped_list+=( $vm )
