Corrections régressions, bugs divers et variés.
database_servers/cluvfy_samples.md
    Le script database_servers/cluster_verify.sh remplace les samples.

virtualbox/compile_guest_additions.sh -> virtualbox/old/compile_guest_additions.sh
    Le script n'est plus utilisé il est déplacé dans old/

README.md
    Typo

database_servers/clone_master.sh
    Correction regression.

database_servers/install_grid.sh
    Réécriture des fonctions lancant les scripts roots.
    Peut-être que le workaround fonctionne...

database_servers/set_ASM_memory_target_low.sh
    Ajuste également le paramètre memory_target

database_servers/run_all.sh
    N'utilise plus le link db mais le chemin incomplet

dg/add_disks_to.sh
    Revu de code et mise à jour doc wiki.

dg/create_new_dg.sh
    Revu de code.

dg/dg_attr.sql
    Ajout du modeline

disk/remove_unused_partition.sh
    Ce script a été supprimé car il fonctionnait mal et je croyais qu'il
    ne servait pas. Il a été réécrit et est fonctionnel.

dg/drop_oracleasm_disks.sh
    Ne fonctionnait plus à cause de la suppression de
    disk/remove_unused_partition.sh
    Correction bug.

dg/remove_file_for_db.sh
    Typo

dg/show_candidat_disks.sql
    Ajout du modeline

dg/show_dg.sql
    Ajout du modeline

disklib.sh
    Fonction get_unused_disks renomée en
get_unused_disks_without_partitions

disk/create_fs.sh
    Renommage fonction get_unused_disks

disk/create_fs_ocfs2.sh
    Renommage fonction get_unused_disks

disk/create_oracleasm_disks_on_new_disks.sh
    Renommage fonction get_unused_disks
    Le paramètre -ilun a été supprimé, le n° du disque oracleasm est
    déduit de l'existant.
    Si kfod est accessible les disques candidats sont affichés.

global.cfg
    Le serveur K2 se synchronise sur internet par défaut.

memory/root_setup_hp.sh
    Correction aide. (script non fiable encore en test)

memory/show_pages.sh
    Fiabilisation de la lecture de l'alertlog (pages mémoire 4K/2M)
    Pour ASM pas de méthode fiable dans la lecture des pages.

ntp/config_ntp.sh
    Correction de la configuration du fichier chrony.conf

plelib.sh
    La fonction exec_cmd affiche le nom du script ou commande qui plante
    plus lisiblement.

san/add_and_export_lv.sh
    Correction bug dans le test de la variable "export_to"

san/export_lv.sh
    BUG dans le code retour du script.

san/save_targetcli_config.sh
    Réactivation des sauvegardes personnelles.

virtualbox/clone_vm.sh
    Ajustement de la taille du disque du grid pour éviter warning de
    cluvfy.

virtualbox/delete_vm
    Revue de code

virtualbox/restart_vboxdrv.sh
    Revue de code

virtualbox/save_vm
    Revue de code

virtualbox/start_vm
    Réécriture du script.

virtualbox/stop_vm
    Revue de code

virtualbox/get_vm_description
    Supprime les 2 premières lignes de la description.

yum/sync_oracle_repository.sh
    BUG le script plantait s'il n'y avait pas de packages à purger.

diff --git a/virtualbox/save_vm b/virtualbox/save_vm
--- a/virtualbox/save_vm
+++ b/virtualbox/save_vm
@@ -20,20 +20,18 @@ then
 fi
 
 typeset -a vm_list
-typeset -i ivm=0
 while read vm_name
 do
-	vm_list[$ivm]=$vm_name
-	ivm=ivm+1
+	[ x"$vm_name" != x ] && vm_list+=( $vm_name )
 done<<<"$(VBoxManage list vms | grep "$server" | cut -d\" -f2)"
 
 typeset -ri max_vms=${#vm_list[@]}
 
 [ $max_vms -eq 0 ] && error "Server for $server not found." && exit 1
 
-for ivm in $( seq 0 $(( max_vms - 1 )) )
+for vm in ${vm_list[*]}
 do
-	exec_cmd -c "VBoxManage controlvm ${vm_list[$ivm]} savestate"
-	[ $? -ne 0 ] && error "Failed to save ${vm_list[$ivm]}"
+	exec_cmd -c "VBoxManage controlvm $vm savestate"
+	[ $? -ne 0 ] && error "Failed to save $vm"
 	LN
 done
diff --git a/virtualbox/start_vm b/virtualbox/start_vm
--- a/virtualbox/start_vm
+++ b/virtualbox/start_vm
@@ -62,50 +62,35 @@ exit_if_param_undef server	"$str_usage"
 
 exit_if_param_invalid wait_os "yes no" "$str_usage"
 
-# $1 vm_name
-function start_db 
-{
-	typeset -r vm_name=$1
-
-	sleep 180
-	db_name=$(ssh oracle@$vm_name ". .profile >/dev/null;\
-						srvctl status database -thisversion" | head -1 | cut -d\  -f4)
-
-	ssh oracle@$vm_name ". .profile >/dev/null;\
-								srvctl start database -db $db_name"
-}
-
+#	Mémorise le nom des VMs correspondant au pattern $server
 typeset -a vm_list
-typeset -i max_vms=0
 while read vm_name
 do
-	[ x"$vm_name" == x ] && continue
-
-	vm_list[$max_vms]=$vm_name
-	max_vms=max_vms+1
+	[ x"$vm_name" != x ] && vm_list+=( $vm_name )
 done<<<"$(VBoxManage list vms | grep "$server" | cut -d\" -f2)"
 
-info "$max_vms server(s) found for pattern $server : ${vm_list[@]}"
-[ $max_vms -eq 0 ] && exit 1
-
-typeset -i nr_vm_started=0
-exec_cmd -c "VBoxManage startvm ${vm_list[0]} --type headless"
-typeset -i vm_last_status=$?	#	Mémorise le status de la dernière VM démarrée.
-[ $vm_last_status -ne 0 ] && error "Failed to start ${vm_list[0]}" || nr_vm_started=1
+info "${#vm_list[@]} server(s) found for pattern $server : ${vm_list[*]}"
 LN
+[ ${#vm_list[@]} -eq 0 ] && exit 1
 
-for i in $( seq 1 $(( max_vms - 1 )) )
+#	Démarre les VMs :
+typeset -i nr_vm_started=0
+for vm in ${vm_list[*]}
 do
-	# Attends que l'OS soit démarré pour éviter le GURU_MEDITATION.
-	[[ $wait_os == yes && $vm_last_status -eq 0 ]] && wait_server ${vm_list[$((i-1))]}
 
-	exec_cmd -c "VBoxManage startvm ${vm_list[$i]} --type headless"
-	vm_last_status=$?
-	[ $vm_last_status -ne 0 ] && error "Failed to start ${vm_list[$i]}" || nr_vm_started=nr_vm_started+1
-	LN
+	line_separator
+	exec_cmd -c "VBoxManage startvm $vm --type headless"
+	if [ $? -eq 0 ]
+	then
+		nr_vm_started=nr_vm_started+1
+		[ $wait_os == yes ] && exec_cmd wait_server $vm && LN || true
+	else
+		error "Failed to start $vm" 
+	fi
+
 done
 
-if [ $nr_vm_started -eq $max_vms ]
+if [ $nr_vm_started -eq ${#vm_list[@]} ]
 then
 	exit 0	# Toutes les VMs ont démarrés.
 else
