Disque en 'RAW ACCESS' possible + lots de corrections
NOTE : il est nécessaire de valider les scripts de création du serveur
       d'infrastructure K2, beaucoup de modifications ont été faite dans
       les scripts.

Résumé :
   Possibilité d'utiliser un disque physique en 'raw access' pour le
   disque du SAN.

   Les problèmes de target au démarrage de K2 et les erreurs aléatoires
   lors des mises à jour avec yum depuis les VMs serveurs semblent être
   résolues en ajoutant juste dans /etc/hosts K2 sur les IPs de
   loopback.

configure_global.cfg.sh
    Test la validité des paramètres.
    Possibilité d'utiliser un disque physique au lieu d'un fichier vdi
    pour le disque du SAN.
    Détecte le nom de l'interface à utiliser pour la NIC eth2 de K2

database_servers/clone_master.sh
    Changement de la taille du stripe des FS utilisé pour stocker les
    fichiers de base de données.
    Ajout de l'option noatime sur les FS contenant les logiciels Oracle & Grid.
    Simplification du code.

disk/create_fs.sh
    Possibilité de préciser l'option -noatime.

db/sql/run_calibrate_io.sh exécute le script db/sql/calibrate_io.sql

global.cfg
    Si la variable san_disk==vdi alors un fichier vdi est utilisé pour le disque
    du SAN.
    Si la variable contient le nom d'un disque alors ce disque est utilisé en
    'raw access' pour le disque du SAN.

san/create_vg.sh
    -add_partition ajoute une partition sur le disque.
    -io_scheduler permet de choisir l'I/O scheduler.

disk/create_udev_rule_io_scheduler.sh
    Permet de créer une règle udev pour choisir l'I/O scheduler d'un disque.

san/drop_san_disk_and_disable_target.sh
    Ignore les erreurs.

setup_first_vms/01_prepare_infra_vm.sh
    Le nom du serveur n'était pas ajouté à /etc/hosts, ce qui semble expliquer
    les erreurs de target et de yum.

setup_first_vms/03_setup_infra_vm.sh
    BUG ne configure plus target si disks_hosted_by==san

setup_first_vms/vbox_scripts/02_install_vm_infra.sh
    Configure le bon 'bridge adaptater' pour l'interface internet du serveur.
    Prend en compte si utilisation d'un disque virtuel ou physique pour le
    disque du SAN.

Service installé sur K2 pour valider le bon fonctionnement de target.
    setup_first_vms/check-target.service
    Le script virtualbox/start_vm_infra n'est donc plus nécessaire, le script
    virtualbox/start_vm traite K2 comme toutes les autres VMs.

Typo : virtualbox/stop_vm

virtualbox/add_disk.sh
    Ajout du paramètre -mtype, util pour ne pas prendre en compte les disques
    du SAN lors des snapshot de VM : -mtype=writethrough

virtualbox/add_raw_disk.sh
    Permet d'attacher un disque en 'raw access' à une VM.

diff --git a/virtualbox/start_vm b/virtualbox/start_vm
--- a/virtualbox/start_vm
+++ b/virtualbox/start_vm
@@ -135,29 +135,23 @@ load_vm_list
 for vm in ${vm_list[*]}
 do
 
-	if [[ "$vm" == "$infra_hostname" && "$INSTALLING_INFRA" != yes ]]
+	exec_cmd -c "VBoxManage startvm $vm --type headless"
+	if [ $? -eq 0 ]
 	then
-		exec_cmd -c "~/plescripts/virtualbox/start_vm_infra"
-		[ $? -eq 0 ] && ((++nr_vm_started)) || true
-	else
-		exec_cmd -c "VBoxManage startvm $vm --type headless"
-		if [ $? -eq 0 ]
-		then
-			((++nr_vm_started))
-			vm_started_list+=( $vm )
-			if [[ $dataguard == yes && ${#vm_list[@]} -eq 1 ]]
-			then # Actuellement seul les serveurs standalone sont en DG.
-				dg_group="$(group_name_for_vm $vm)"
-				if [ "${dg_group:0:2}" == "DG" ]
-				then
-					load_vm_in_group "$dg_group" "$vm"
-				fi
+		((++nr_vm_started))
+		vm_started_list+=( $vm )
+		if [[ $dataguard == yes && ${#vm_list[@]} -eq 1 ]]
+		then # Actuellement seul les serveurs standalone sont en DG.
+			dg_group="$(group_name_for_vm $vm)"
+			if [ "${dg_group:0:2}" == "DG" ]
+			then
+				load_vm_in_group "$dg_group" "$vm"
 			fi
-		else
-			error "Failed to start $vm" 
 		fi
-		LN
+	else
+		error "Failed to start $vm" 
 	fi
+	LN
 
 done
 
