Corrections suite aux tests sur la shm.
global.cfg                : réhabilitation de hack_asm_memory
show_pages.sh             : maj
02_update_config.sh       : positionne la locale de l'OS à en_US pratique pour les logs de l'OS.
clone_vm.sh               : activation du hotplug cpu
restart_vboxdrv.sh        : redémarre absolument tous les composants VBox.
start_vm                  : GURU_MEDITATION supprimé.
stop_vm                   : bugs corrigés.
sync_oracle_repository.sh : messages plus clairs
update_master.sh          : utilise davantage exec_cmd

diff --git a/virtualbox/start_vm b/virtualbox/start_vm
--- a/virtualbox/start_vm
+++ b/virtualbox/start_vm
@@ -40,38 +40,26 @@ function virtualbox_start
 
 	typeset -i nr_vm_started=0
 	exec_cmd -c "VBoxManage startvm ${vm_list[0]} --type headless"
-	typeset -i vm_started=$?
-	[ $vm_started -ne 0 ] && error "Failed to start ${vm_list[0]}" || nr_vm_started=1
+	typeset -i vm_last_status=$?
+	[ $vm_last_status -ne 0 ] && error "Failed to start ${vm_list[0]}" || nr_vm_started=1
 	LN
 
 	for i in $( seq 1 $(( max_vms - 1 )) )
 	do
-		if [ $vm_started -eq 0 ]
-		then
-			if [ "$GURU_MEDITATION" == "1" ]
-			then
-				info "sudo systemctl restart vboxdrv, peut résoudre le problème..."
-				info "Attend le démarrage du crs pour éviter le 'GURU MEDITATION'"
-
-				show_grid_status -server=${vm_list[$((i-1))]} -wait_time_secs=60
-				LN
-			else
-				info "La variable GURU_MEDITATION n'est pas définie, pas d'attente du crs."
-				wait_server ${vm_list[$((i-1))]}
-			fi
-		fi
+		# Attends que l'os soit démarrer pour éviter le GURU_MEDITATION.
+		[ $vm_last_status -eq 0 ] && wait_server ${vm_list[$((i-1))]}
 
 		exec_cmd -c "VBoxManage startvm ${vm_list[$i]} --type headless"
-		vm_started=$?
-		[ $vm_started -ne 0 ] && error "Failed to start ${vm_list[$i]}" || nr_vm_started=nr_vm_started+1
+		vm_last_status=$?
+		[ $vm_last_status -ne 0 ] && error "Failed to start ${vm_list[$i]}" || nr_vm_started=nr_vm_started+1
 		LN
 	done
 
-	if [ $vm_started -eq 0 ]
+	if [ $nr_vm_started -eq $max_vms ]
 	then
-		return 0
+		return 0	# Toutes les VMs ont démarrés.
 	else
-		return 1
+		return 1	# Au moins une VM n'a pas démarré.
 	fi
 }
 
