Augment le temps d'attente pour éviter le GURU MEDIDATION de VirtualBox

diff --git a/virtualbox/start_vm b/virtualbox/start_vm
--- a/virtualbox/start_vm
+++ b/virtualbox/start_vm
@@ -46,7 +46,7 @@ function virtualbox_start
 			info "sudo systemctl restart vboxdrv, peut résoudre le problème..."
 			info "Attend le démarrage du crs pour éviter le 'GURU MEDITATION'"
 
-			show_grid_status -wait_time_secs=30 -node=$i
+			show_grid_status -wait_time_secs=60 -node=$i
 			LN
 		else
 			info "La variable GURU_MEDITATION n'est pas définie, pas d'attente du crs."
@@ -54,7 +54,17 @@ function virtualbox_start
 		fi
 
 		exec_cmd "VBoxManage startvm ${vm_list[$i]} --type headless"
-		[ $? -ne 0 ] && error "Failed to start ${vm_list[$i]}" || nr_vm_started=nr_vm_started+1
+		if [ $? -ne 0 ]
+		then
+			error "Failed to start ${vm_list[$i]}"
+		else
+			nr_vm_started=nr_vm_started+1
+			if [ $nr_vm_started -eq $max_vms ]
+			then
+				wait_server ${vm_list[$i]}
+				show_grid_status -wait_time_secs=60 -node=$((i+1))
+			fi
+		fi
 		LN
 	done
 }
