Démarre/arrête tous les serveurs d'un cluster dataguard
Ajout du paramètre -dataguard, vaut yes par défaut.
	virtualbox/start_vm
	virtualbox/stop_vm

Ajout du paramètre -dataguard=no aux scripts [stop|start]_vm
Les scripts n'ont pas été testés.
	database_servers/clone_master.sh
	setup_first_vms/vbox_scripts/02_install_vm_infra.sh
	setup_first_vms/vbox_scripts/03_install_vm_master.sh
	virtualbox/reboot_vm

diff --git a/virtualbox/stop_vm b/virtualbox/stop_vm
--- a/virtualbox/stop_vm
+++ b/virtualbox/stop_vm
@@ -2,17 +2,11 @@
 # vim: ts=4:sw=4
 
 . ~/plescripts/plelib.sh
+. ~/plescripts/usagelib.sh
 . ~/plescripts/global.cfg
 EXEC_CMD_ACTION=EXEC
 
 typeset -r ME=$0
-typeset -r str_usage=\
-"Usage : $ME
-	-server=<nom de la VM> si omis essait la variable ID_DB
-	[-wait_os=yes] : no n'aattend pas que l'OS soit stoppé avant de rendre la main.
-	[-reboot_vbox] : reboot tous les composants de vbox.
-	[-error_on_poweroff] : si un poweroff est nécessaire retourn 1
-"
 
 script_banner $ME $@
 
@@ -20,6 +14,18 @@ typeset server=undef
 typeset	wait_os=yes
 typeset reboot_vbox=no
 typeset error_on_poweroff=no
+typeset	dataguard=yes
+
+add_usage "[-server=name]"			"Si non définie testera ID_DB (cf set_db)"
+add_usage "[-dataguard=$dataguard]"	"yes|no, yes : arrête toutes les VMs du dataguard."
+add_usage "[-wait_os=$wait_os]"		"yes|no, yes : attend l'arrêt complet de l'OS avant de poursuivre."
+add_usage "[-reboot_vbox]"			"Reboot tous les composants de vbox."
+add_usage "[-error_on_poweroff]"	"Si un poweroff est nécessaire retourne 1"
+
+typeset -r str_usage=\
+"Usage : $ME
+$(print_usage)
+"
 
 while [ $# -ne 0 ]
 do
@@ -49,6 +55,11 @@ do
 			shift
 			;;
 
+		-dataguard=*)
+			dataguard=${1##*=}
+			shift
+			;;
+
 		-h|-help|help)
 			info "$str_usage"
 			LN
@@ -70,7 +81,7 @@ do
 	esac
 done
 
-[[ $server == undef ]] && [[ -v ID_DB ]] && server=$ID_DB
+[[ $server == undef && -v ID_DB ]] && server=$ID_DB || true
 exit_if_param_undef server	"$str_usage"
 
 function wait_os_until_stopped
@@ -115,59 +126,120 @@ function wait_os_until_stopped
 	show_cursor
 }
 
+#	$1 vm name
+#	print group name to stdout
+function group_name_for_vm
+{
+	VBoxManage showvminfo "$1" | grep -E "^Groups:" | cut -d/ -f2-
+}
+
+#	$1 group name
+#	$2 vm name to exclude
+#	register all VMs in group $1 to dataguard_list
+#	Declare dataguard_list before to call function : typeset -a dataguard_list
+function load_vm_in_group
+{
+	typeset -r search_group="$1"
+	typeset	-r exclude="$2"
+
+	while read vm_name
+	do
+		[[ x"$vm_name" == x || "$vm_name" == "$exclude" ]] && continue || true
+
+		if [ "$(group_name_for_vm $vm_name)" == "$search_group" ]
+		then
+			dataguard_list+=( $vm_name ) 
+		fi
+	done<<<"$(VBoxManage list vms | cut -d\" -f2)"
+}
+
+#	$1 vm name
+function stop_vm_name
+{
+	typeset -r vm_to_stop="$1"
+
+	exec_cmd -c "VBoxManage controlvm $vm_to_stop acpipowerbutton"
+	if [ $? -ne 0 ]
+	then
+		error "Failed to stop $vm_to_stop"
+		LN
+
+		if [ $error_on_poweroff == yes ]
+		then
+			((++count_errors))
+		else
+			line_separator
+			info "Poweroff : $vm_to_stop"
+			exec_cmd -c "VBoxManage controlvm $vm_to_stop poweroff"
+			if [ $? -ne 0 ]
+			then
+				error "Failed to poweroff $vm_to_stop"
+				((++count_errors))
+			fi
+		fi
+	else
+		vm_stopped_list+=( $vm_to_stop )
+	fi
+}
+
 #===============================================================================
 #	Charge le nom des VMs dans vm_list
 
 typeset -a vm_list	#	Contient le nom de toutes les VMs
+typeset -a vm_stopped_list
+typeset	-a dataguard_list
+typeset -i count_errors=0
 
 while read vm_name
 do
 	[ x"$vm_name" != x ] && vm_list+=( $vm_name )
 done<<<"$(VBoxManage list runningvms | grep "$server" | cut -d\" -f2)"
 
-typeset -ri max_vms=${#vm_list[@]}
+typeset -i max_vms=${#vm_list[@]}
 info "$max_vms running VMs found for pattern $server : ${vm_list[@]}"
 LN
-[ $max_vms -eq 0 ] && exit 0
+
+[ $max_vms -eq 0 ] && exit 0 || true
+
+unset max_vms # ne doit plus être utilisé, la taille de la liste pour varier.
 
 #===============================================================================
 # Stop les VMs et mémorise leur nom dans vm_stopped_list
-
-typeset -a vm_stopped_list
-
-typeset -i count_errors=0
 
 line_separator
 #	Stop toutes les VMs
 for vm in ${vm_list[@]}
 do
-	exec_cmd -c "VBoxManage controlvm $vm acpipowerbutton"
-	if [ $? -ne 0 ]
-	then
-		error "Failed to stop $vm"
-		LN
+	stop_vm_name "$vm"
 
-		if [ $error_on_poweroff == yes ]
+	if [[ $dataguard == yes && ${#vm_list[@]} -eq 1 ]]
+	then # Actuellement seul les serveurs standalone sont en DG.
+		dg_group="$(group_name_for_vm $vm)"
+		if [ "${dg_group:0:2}" == "DG" ]
 		then
-			count_errors=count_errors+1
-		else
-			line_separator
-			info "Poweroff : $vm"
-			exec_cmd -c "VBoxManage controlvm $vm poweroff"
-			if [ $? -ne 0 ]
-			then
-				error "Failed to poweroff $vm"
-				count_errors=count_errors+1
-			fi
+			load_vm_in_group "$dg_group" "$vm"
 		fi
-	else
-		vm_stopped_list+=( $vm )
 	fi
+
 	LN
 done
 
+#	============================================================================
+#	Arrête les éventuelles autres VMs du dataguard.
+if [ ${#dataguard_list[@]} -ne 0 ]
+then
+	line_separator
+	info "Stop dataguard members : ${dataguard_list[*]}"
+	for vm_name in ${dataguard_list[*]}
+	do
+		vm_list+=( $vm_name )
+		stop_vm_name "$vm_name"
+		LN
+	done
+fi
+
 #===============================================================================
-if [ $wait_os == yes ]
+if [[ $EXEC_CMD_ACTION == EXEC && $wait_os == yes ]]
 then	# Attend que toutes les VMs soient stoppée.
 	typeset -ri	stop_at=$SECONDS
 	line_separator
