Un seul paramètre il est considéré comme un pattern de serveur.

diff --git a/virtualbox/stop_vm b/virtualbox/stop_vm
--- a/virtualbox/stop_vm
+++ b/virtualbox/stop_vm
@@ -44,10 +44,16 @@ do
 			;;
 
 		*)
-			error "Arg '$1' invalid."
-			LN
-			info "$str_usage"
-			exit 1
+			if [ $server == undef ]
+			then
+				server=$1
+				shift
+			else
+				error "Arg '$1' invalid."
+				LN
+				info "$str_usage"
+				exit 1
+			fi
 			;;
 	esac
 done
